# Generated by Django 3.2.13 on 2022-05-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.SmallIntegerField()),
                ('last_update', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='films.film')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('store_id', models.SmallIntegerField()),
                ('active', models.BooleanField()),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('last_update', models.DateTimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.address')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.address')),
                ('manager_staff', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.staff')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.inventory')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.staff')),
            ],
            options={
                'db_table': 'rental',
                'unique_together': {('rental_date', 'inventory', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.rental')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.staff')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
